Import('env', 'install')

local_env = env.Clone()
local_env.Append(
    LIBPATH = ['level_editor', 'core'],
    LIBS = ['level_editor', 'core'])

install.AddProgram(local_env.Program('#dist/gonstruct', []))

SConscript(['core/SConscript', 'level_editor/SConscript'],
           exports = ['env', 'install'])
